export class PlacementShortListStudentResponseModel {
  public Selected: boolean = false;
  public StudentID: number = 0;
  public StudentName: string = '';
  public EnrollmentNo: string = '';
  public Email: string = '';
  public FatherName: string = '';
  public DOB: string = '';
  public Age: number = 0;
  public Dis_Gender: string = '';
  public Cast: string = '';
  public MobileNo: string = '';
  public StateName: string = '';
  public InstitutionManagementType: string = '';
  public InstituteName: string = '';
  public BranchName: string = '';
  public DistrictName: string = '';
  public MartialStatus: string = '';
  public Email_2: string = '';
  public WhatAppNo: string = '';
  public Height: number = 0;
  public weight: number = 0;
  public Pre_10th: number = 0;
  public PassYear_10th: number = 0;
  public Pass_12th: string = '';
  public Pre_12th: number = 0;
  public PassYear_12th: number = 0;
  public Stream_12th: string = '';
  public Pass_ITI: string = '';
  public Pre_ITI: number = 0;
  public PassYear_ITI: number = 0;
  public Qualification: string = '';
  public AdmissionYear: number = 0;
  public AdmissionMode: string = '';
  public Pre_1stSem: number = 0;
  public Pre_2stSem: number = 0;
  public Pre_3stSem: number = 0;
  public Pre_4stSem: number = 0;
  public Pre_5stSem: number = 0;
  public Pre_6stSem: number = 0;
  public BackPaper: number = 0;
  public SingleAttempt: string = '';
  public Pre_Aggregate: number = 0;
  public PassingYear: string = '';
  public AnyExperience: string = '';
  public CompanyName: string = '';
  public CompanyLocation: string = '';
  public Designation: string = '';
  public CampusPostID: number = 0;
  public HiringRole: number = 0;
  public ExperienceFiledType: string = '';
  public TotalExperience: number = 0;
  public Salary_CTC: number = 0;
  public ApprenticeCompleted: string = '';
  public Marked: boolean = false;
  public ModifyBy: number = 0
  public IPAddress: string = ''
  public PostNo: string = ''
}

export class PlacementShortlistedStuSearch {
  public RoleId: number = 0;
  public UserId: number = 0;
  public BranchID: number = 0
  public DepartmentID: number = 0
  public Eng_NonEng: number = 0
  public CampusPostID:number=0
}
